export {
  getData,
  FETCH_SMURFS_DATA_START,
  FETCH_SMURFS_DATA_SUCCESS,
  FETCH_SMURFS_DATA_FAILURE,
  storeData,
  POST_SMURFS_DATA_START,
  POST_SMURFS_DATA_SUCCESS,
  POST_SMURFS_DATA_FAILURE,
} from './smurfActions';
